### ISSUE TITLE
Compile errors when using it for MKR ZERO

### ISSUE THREAD

**Issue by jaapcammeraat** [n0mjs710/MCP23S17#20]
/Users/jaap/Documents/Arduino/libraries/MCP23S17/MCP23S17.cpp: In member function 'void MCP::begin()':
/Users/jaap/Documents/Arduino/libraries/MCP23S17/MCP23S17.cpp:87:27: error: invalid conversion from 'int' to 'PinStatus' [-fpermissive]
   ::digitalWrite(_ss, HIGH);            // Set SlaveSelect HIGH (chip de-selected)
                           ^
In file included from /Users/jaap/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Interrupts.h:8:0,
                 from /Users/jaap/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/ArduinoAPI.h:29,
                 from /Users/jaap/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/Arduino.h:23,
                 from /Users/jaap/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/libraries/SPI/SPI.h:23,
                 from /Users/jaap/Documents/Arduino/libraries/MCP23S17/MCP23S17.cpp:43:
/Users/jaap/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Common.h:95:6: note:   initializing argument 2 of 'void digitalWrite(pin_size_t, PinStatus)'
 void digitalWrite(pin_size_t pinNumber, PinStatus status);
      ^~~~~~~~~~~~

**Comment by n0mjs710** [comment]
Yep, it doesn’t work on every possible board. Definitely ones I don’t have.
