### ISSUE TITLE
pinMode(uint16_t) works in the opposite way than intended

### ISSUE THREAD

**Issue by GioCC** [n0mjs710/MCP23S17#3]
The version of pinMode() with word argument has an uncalled for negation of the argument, therefore it configures inputs and outputs reversed!

**Comment by janakelarsson** [comment]
Yes, INPUT is =1, both the arduino #define and on a MCP23S17. The below will fix it, I'll do a pull request soon.

[MCP23S17.patch.txt](https://github.com/n0mjs710/MCP23S17/files/909970/MCP23S17.patch.txt)

**Comment by janakelarsson** [comment]
This has re-appeared recently, it seems a patch from October 2017 restores the older, wrong behavior. Could someone explain why?

**Comment by janakelarsson** [comment]
Did not reopen on comment, I'll open a new issue.
