### ISSUE TITLE
Using library on arduino micro

### ISSUE THREAD

**Issue by vince87** [n0mjs710/MCP23S17#7]
hello, i tried your library, but with arduino micro does not work the addresses.
The first ic, work well, while the other sends and receives random data!
The first ic have A0,A1,A2 to 0, the second A0 to vcc A1,A2 to 0
Any suggestion?
Thanks
Vincenzo

**Comment by n0mjs710** [comment]
I don't have an Arduino micro, so can't do your troubleshooting for you. Can't see any reason why it should be a problem, but again, don't have a ATmega32u4 based board to test with.

Current GitHub version (as of right now) tested with the following code and worked fine. If you want to discuss further, send me an email directly. 

#include <MCP23S17.h>
#include <SPI.h>

MCP one(0,10);
MCP two(3,10);

void setup() {
  one.begin();
  two.begin();
  for (uint8_t i=1; i<17; i++) {
    one.pinMode(i, OUTPUT);
    two.pinMode(i, INPUT);
    two.pullupMode(i, HIGH);
  }
}

void loop() {
  for (uint8_t i=0; i<2; i++) {
    for (uint8_t p=1; p<17; p++) {
      one.digitalWrite(p, HIGH);
      if (p>0) {
        one.digitalWrite(p-1, LOW);
      }
      delay(100);
    }
    one.digitalWrite(16, LOW);
  }

  while (true) {
    for (uint8_t i=1; i<17; i++) {
      one.digitalWrite(i, two.digitalRead(i));
    }
  }
}
